name: Telegram и HTML5-Validator
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Уведомление и валидация
    runs-on: ubuntu-latest
    steps:
    - name: Send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ s@CptDno }}
        token: ${{ secrets.@cptDno_ci_cd_bot }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Пройти проверки HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action-experimental@master
      with:
        root: /
      continue-on-error: true
